// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWFktcXXUtFG5rePrq6Wq_heDMo3cYBrs',
    appId: '1:85269677127:android:89af600ec4bfa8df9a1d62',
    messagingSenderId: '85269677127',
    projectId: 'reiseapp-mamatocherontour',
    storageBucket: 'reiseapp-mamatocherontour.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlCfr6X3q_qvMtK7ePjsIaDQzJ2ekyljI',
    appId: '1:85269677127:ios:9ae6aaac2af69a9d9a1d62',
    messagingSenderId: '85269677127',
    projectId: 'reiseapp-mamatocherontour',
    storageBucket: 'reiseapp-mamatocherontour.firebasestorage.app',
    androidClientId: '85269677127-d7abbgic474h8s27il55li3bqamtnbt3.apps.googleusercontent.com',
    iosClientId: '85269677127-s20qhf4m07pl3d01upnc3rlrt7cd2bcn.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.reisetagebuch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlCfr6X3q_qvMtK7ePjsIaDQzJ2ekyljI',
    appId: '1:85269677127:ios:9ae6aaac2af69a9d9a1d62',
    messagingSenderId: '85269677127',
    projectId: 'reiseapp-mamatocherontour',
    storageBucket: 'reiseapp-mamatocherontour.firebasestorage.app',
    androidClientId: '85269677127-d7abbgic474h8s27il55li3bqamtnbt3.apps.googleusercontent.com',
    iosClientId: '85269677127-s20qhf4m07pl3d01upnc3rlrt7cd2bcn.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.reisetagebuch',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoBJKv2nutJU4ykMcHrpaGjDa86L3bGZ0',
    appId: '1:85269677127:web:8cdf91178639aaf79a1d62',
    messagingSenderId: '85269677127',
    projectId: 'reiseapp-mamatocherontour',
    authDomain: 'reiseapp-mamatocherontour.firebaseapp.com',
    storageBucket: 'reiseapp-mamatocherontour.firebasestorage.app',
    measurementId: 'G-99DNSQ38XW',
  );

}